<a href="https://colab.research.google.com/github/lucasdonizete/MetodosNumericos/blob/master/Elimina_Gauss_version_01_LucasDSilva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import time
import matplotlib.pyplot as plt
import numpy.linalg as npla


########################################################
# Function to decompose the matrix
# in an upper triangular form
########################################################

def LU(A,f):
  # get the size of the system
  n = len(f)
  
  # check the size
  
  if (A.shape[0] != n) or (A.shape[1] != n):
    print('\t Inconsistent size in LU decomposition')
    info = 0
    return M,info

  # create the augmented matrix
  M = np.zeros((n,n+1))
  M[:,:-1] = A
  M[:,-1] = f

  # loop through all the colum
  # to get rid of the lower part
  for iC in range(n-1):
    # for each column loop over all the lines
    # that are below the diagonal
    # to set to 0 their elements
    for iL in range(iC+1,n):
      # check if the diagonal element
      # is null
      if(M[iC,iC] == 0):
        print('\t Zero on the diagonal, LU failed')
        info = 0
        return M,info
      # eliminate the element
      M[iL,:] = M[iL,:] - M[iL,iC]/M[iC,iC] * M[iC,:]

   # if we succed we return info = 1 and the upper augmetned matrix

  info = 1
  return M,info
      

In [34]:
########################################################
# Function to backsubstitute the results
# and get the final solution
########################################################
def BS(M):
  # get the size of the matrix
  n = M.shape[0]
  # loop over all the lines
  # starting by the end
  for iL in range(n-1,-1,-1):
    # check if we have diagonal elements on the diagonal
    if(M[iL,iL] == 0):
      print('\t Zero on the diagonal, LU failed')
      info = 0
      return M,info
    # divide the line by the diagonal element of M
    M[iL,:] /= M[iL,iL]
    
    # loop over all the lines that are above this onef
    for iLL in range(iL-1,-1,-1):
      M[iLL,:] -= M[iLL,iL]*M[iL,:]

  info = 1
  return M,info

########################################################
########################################################

In [35]:
# create the matrix A
A = np. array ([[1 ,1 ,0, 0] ,[-220, 0, 1, 0] , [0, -0.3, 0, 1], [0, 0, 1, 1]])

# create the right-hand side
feed = np. array ([1 ,0 ,0, 1])

M,info = LU(A,feed)
x,info = BS(M)

# print the solution
print(x)

# check the solution
check_sol = np.dot(A,x)
print(check_sol) 


[[ 1.          0.          0.          0.          0.00318616]
 [ 0.          1.          0.          0.          0.99681384]
 [ 0.          0.          1.          0.          0.70095585]
 [-0.         -0.         -0.          1.          0.29904415]]
[[ 1.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
   1.00000000e+00]
 [-2.20000000e+02  0.00000000e+00  1.00000000e+00  0.00000000e+00
   8.21565038e-15]
 [ 0.00000000e+00 -3.00000000e-01  0.00000000e+00  1.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+00
   1.00000000e+00]]


In [36]:
# create the matrix B
B = np. array ([[1,1,-1],[0.70095585, 0.00318616, -0.1] , [0,0,0.1]])

# create the right-hand side
alimenta = np. array ([0, 0, 10])

N,info = LU(B,alimenta)
a,info = BS(N)

# print the solution
print(a)

# check the solution
check_sol = np.dot(B,a)
print(check_sol) 

[[  1.           0.           0.          13.87475572]
 [ -0.           1.          -0.          86.12524428]
 [  0.           0.           1.         100.        ]]
[[ 1.00000000e+00  1.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [ 7.00955850e-01  3.18616000e-03 -1.00000000e-01 -2.33146835e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e-01  1.00000000e+01]]
